feat: support list and add in .git directories
While 'git worktree list' and 'git worktree add' work when invoked
inside the .git directory, git-wt fails because it cannot determine
the current worktree in that case:

    $ git wt
    Error: failed to get current location: exit status 128

    $ git wt foo
    Error: failed to create worktree: exit status 128

Detect when git-wt is invoked inside the .git directory and use the
main repository root in that case.